### ISSUE TITLE
Call onChange on keyboard event

### ISSUE THREAD

**Issue by hilo2120** [mberneti/react-datepicker2#96]
It seems that when you change date input using keyboard, input value changes but the onChange function doesn't get fired.
The ability to change date directly from input looks very handy and important

**Comment by mberneti** [comment]
@hilo2120 What do you think about firing onChange handle after clicking on the enter key?

**Comment by hilo2120** [comment]
@mberneti I think clicking the enter key to confirm date change is a little bit odd for regular users, And there may be conflicts with form submission in some scenarios,
I believe firing onChange right after input change would be a better solution

**Comment by mberneti** [comment]
@hilo2120 It's possible to have invalid input (not completed date) and in this state, we should not fire onChange with an invalid value.
On the other hand, I know after a "final point", we should have a valid date that is the same as the input text, this final point should be at the end of the user typing because It may cause a rollback and change the input

**Comment by aliazizi** [comment]
It was fixed in
https://github.com/mberneti/react-datepicker2/pull/95

code:
https://github.com/mberneti/react-datepicker2/blob/1dda95a295bf066a0da3eb245b3e86afbb1a7250/src/components/DatePicker.js#L234

I also add `onInputChange` props that fire as user typing ( in case don't you want to set state in `blur` )

**Comment by hilo2120** [comment]
@aliazizi I'm using the latest version (3.2.0) that is published 3 months ago according to npmjs.com.
There is no onBlur in this version for DatePicker.
Maybe you haven't published the changes as a new version?

**Comment by mberneti** [comment]
@hilo2120 I'll do it today.

**Comment by hilo2120** [comment]
@mberneti Can we validate input content after every change? I mean not onBlur, exactly on input change.
I think updating state value "onChange" is safer than "onBlur" for some special uses like updating another component in realtime.
I don't know if it really is a better approach, I just think it is!

**Comment by aliazizi** [comment]
> 
> 
> @aliazizi I'm using the latest version (3.2.0) that is published 3 months ago according to npmjs.com.
> There is no onBlur in this version for DatePicker.
> Maybe you haven't published the changes as a new version?

you can use `"react-datepicker2": "mberneti/react-datepicker2#pull/95/head",` in your package.json until the release is ready




> 
> 
> @mberneti Can we validate input content after every change? I mean not onBlur, exactly on input change.
> I think updating state value "onChange" is safer than "onBlur" for some special uses like updating another component in realtime.
> I don't know if it really is a better approach, I just think it is!

I think there is a lot more complex that than `onBlur`. If user enter the wrong date, the date should convert to valid format because of validation, right? and user can't change input because of that. ( for example if user start typing in blank input and add first char for year, the input will changed to valid date ( because one char is not valid )

because of this problem I add it in blur. when user

**Comment by hilo2120** [comment]
@aliazizi Thanks for the pull usage instruction, I didn't know that.

> I think there is a lot more complex that than `onBlur`. If user enter the wrong date, the date should convert to valid format because of validation, right? and user can't change input because of that. ( for example if user start typing in blank input and add first char for year, the input will changed to valid date ( because one char is not valid ) )

Yes your'e right, but the same problem exists for `onBlur`, for example user edits input and puts just a 1 in it and blurs out. What happens to validation?
I will work on `onChange` option and create a pull request if I could make it work as I expected. It's definitely worth a shot.
Thanks a lot @mberneti @aliazizi

**Comment by mberneti** [comment]
@aliazizi I published a new version of react-datepicker2 on the npm based on @aliazizi PR #95

**Comment by mberneti** [comment]
@hilo2120 You can see onInputChange usage [here](https://mberneti.github.io/react-datepicker2/#example-14) on the Demo page.

**Comment by hilo2120** [comment]
@mberneti This behaviour is exactly what I was looking for.
Thanks for updating package and useful demo.
